name: "build"
on:
  push:
    branches:
      - main

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
#        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: install dependencies
      run: |
        cargo install cross --git https://github.com/cross-rs/cross
#    - name: build it
#      run: cargo tauri build

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker Buildx
      run: docker system prune && docker build -t rustcross:dbus-armhf .
    - name: build it for raspberry pi
      if: matrix.platform == 'ubuntu-latest'
      run: |
        readonly TARGET_ARCH=armv7-unknown-linux-gnueabihf
        readonly LINK_FLAGS='-L /usr/arm-linux-gnueabihf/lib/ -L /usr/lib/arm-linux-gnueabihf/'
        RUSTFLAGS=${LINK_FLAGS} cross build --release --target=${TARGET_ARCH}
        cross build
#        sudo apt install gcc-8-multilib-arm-linux-gnueabihf
#        rustup target add armv7-unknown-linux-gnueabihf

